update nasca.ficha f
set
fila=fd.fila,
sucursal=fd.sucursal,
estado_conexion=fd.estado_conexion,
codsuministro=fd.codsuministro,
distrito=fd.distrito,
sector=fd.sector,
manzana=fd.manzana,
lote=fd.lote,
conexion=fd.conexion,
sector_opera=fd.sector_opera,
subsector=fd.subsector,
tipo_habilitacion=fd.tipo_habilitacion,
nombre_habilitacion=fd.nombre_habilitacion,
manzana_mun=fd.manzana_mun,
lote_mun=fd.lote_mun,
sublote_mun=fd.sublote_mun,
tipo_poblacion=fd.tipo_poblacion,
tipo_via=fd.tipo_via,
nombre_via=fd.nombre_via,
num_municipal=fd.num_municipal,
telefono=fd.telefono,
estado_servicio=fd.estado_servicio,
tipo_servicio=fd.tipo_servicio,
referencias=fd.referencias,
tipo_construccion=fd.tipo_construccion,
estado_construccion=fd.estado_construccion,
grupo_caracteristico=fd.grupo_caracteristico,
ciiu=fd.ciiu,
quien_habita=fd.quien_habita,
num_familias=fd.num_familias,
num_habitantes=fd.num_habitantes,
estado_agua=fd.estado_agua,
categoria_agua=fd.categoria_agua,
tipo_cobranza_medicion=fd.tipo_cobranza_medicion,
macrosector_agua=fd.macrosector_agua,
sector_agua=fd.sector_agua,
multiusuario_agua=fd.multiusuario_agua,
cantidad_predios=fd.cantidad_predios,
caja_registro=fd.caja_registro,
estado_caja_agua=fd.estado_caja_agua,
acometida_tuberia=fd.acometida_tuberia,
diametro_acometida=fd.diametro_acometida,
tapa=fd.tapa,
tipo_consumidor=fd.tipo_consumidor,
pavimento=fd.pavimento,
localizacion_conexion=fd.localizacion_conexion,
ubicacion_metros=fd.ubicacion_metros,
fuga=fd.fuga,
estado_tapa=fd.estado_tapa,
estado_desague=fd.estado_desague,
categoria_desague=fd.categoria_desague,
macrosector_desague=fd.macrosector_desague,
sector_desague=fd.sector_desague,
red_distribucion_desague=fd.red_distribucion_desague,
tipo_material_tuberia=fd.tipo_material_tuberia,
diametro_tubo=fd.diametro_tubo,
tipo_caja=fd.tipo_caja,
estado_caja=fd.estado_caja,
localizacion_caja=fd.localizacion_caja,
estado_obstruido=fd.estado_obstruido,
ubicacion_metros_desague=fd.ubicacion_metros_desague,
marca_medidor=fd.marca_medidor,
num_medidor=fd.num_medidor,
lectura=fd.lectura,
diametro_medidor=fd.diametro_medidor,
estado_medidor=fd.estado_medidor,
posicion_medidor=fd.posicion_medidor,
tipo_medidor=fd.tipo_medidor,
valvula=fd.valvula,
seguridad_medidor=fd.seguridad_medidor,
vereda=fd.vereda,
pista=fd.pista,
pozo_artesanal=fd.pozo_artesanal,
tipo_almacenamiento=fd.tipo_almacenamiento,
num_pisos=fd.num_pisos,
presion_agua=fd.presion_agua,
medidas_fachada=fd.medidas_fachada,
frec_horas_abastecimiento=fd.frec_horas_abastecimiento,
frec_dias_abastecimiento=fd.frec_dias_abastecimiento,
observaciones=fd.observaciones,
codencuestador=fd.codencuestador,
fectrabajada=fd.fectrabajada
from nasca.ficha_dev fd
where f.codsuministro = fd.codsuministro and fd.codsuministro <> '' --Los que ya estan cargados








